### ISSUE TITLE
Reuse EC2 instances

### ISSUE THREAD

**Issue by sytham** [openai/rllab#108]
Hi, currently when running experiments on EC2 using `run_experiment_lite`, a new EC2 instance is created for each call to `run_experiment_lite` and then terminated (if `terminate_machine=True`). I was wondering if it's possible to re-use existing instances, i.e. to set `terminate_machine=False` and then launch another experiment on it. Just by reading the code it seems this is currently not possible, correct?

The reason I ask is that creating and terminating instances can get expensive very quickly since Amazon rounds up costs to whole hours. So say I have 100 hyper parameter sets to evaluate, and one experiment run takes 5 minutes, in the current setup I'm going to have to pay 100 * hourly_cost anyway, no matter how I approach it, even though CPU time is only 8.3 hours.

**Comment by dementrock** [comment]
There's no current support for this. However what you can do is to group multiple jobs on one instance, by setting the batch_tasks argument: https://github.com/openai/rllab/blob/master/rllab/misc/instrument.py#L340

**Comment by sytham** [comment]
Okay thanks!
