### ISSUE TITLE
Parameterized should be Serializable?

### ISSUE THREAD

**Issue by sytham** [openai/rllab#113]
`rllab.core.parameterized.Parameterized` currently fails on `__getstate__ `for objects that extend `Parameterized` but do not extend `Serializable`, specifically with error:

`AttributeError:  object has no attribute '_Serializable__args'`

(as a side note, `Serializable` causes issues for me, hence I ran into this). So it seems to me that `Parameterized` should enforce subclasses to be `Serializable` by subclassing `Serializable` itself; given that it already implements `__getstate__` this also makes sense.

I could do this but not sure what other things this might break or why it was set up this way.

**Comment by sytham** [comment]
Just another comment on the sidenote above: I have now solved my serialization issues by not letting my policy inherit from the rllab base classes (`Parameterizable`, Seriali`z`able etc). However, now I'm nervous that this might cause trouble elsewhere. So, what's the reason this serialization mechanism through `__getstate__` and `__setstate__` is used, instead of the default pickling mechanism? I'm running this in parallel without this now and it seems to work fine.

**Comment by dementrock** [comment]
It depends on how you implement the policy, but sometimes default pickling can have trouble. The proper way to inherit from Parameterized / Serializable, is to have your own policy class inherit from Serializable too, and call `Serializable.quick_init(self, locals())` as the first statement in your `__init__` method.

**Comment by sytham** [comment]
Yeah, that's what I did. The short story of why that didn't work for me
seems to be that one of the policy attributes is an external object that
points back at the policy. Default pickling does seem to work.
In which circumstances can default pickling have trouble?

On Apr 15, 2017 12:26 AM, "Rocky Duan" <notifications@github.com> wrote:

It depends on how you implement the policy, but sometimes default pickling
can have trouble. The proper way to inherit from Parameterized /
Serializable, is to have your own policy class inherit from Serializable
too, and call Serializable.quick_init(self, locals()) as the first
statement in your __init__ method.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openai/rllab/issues/113#issuecomment-294248243>, or mute
the thread

**Comment by dementrock** [comment]
Sometimes when policy references external C libraries. I've also found issues with serializing theano / tensorflow policies, but I'm glad it worked for you.

**Comment by sytham** [comment]
Okay thanks. I also have a policy that references an external C library so I'll keep that in mind.

In any case, this was the side note :) It's still the case that `rllab.core.parameterized.Parameterized` currently fails on `__getstate__` for objects that extend `Parameterized` but do not extend `Serializable`. I understand that the proper way of doing it is to subclass both (even though in my case I'd like to subclass only one), but if that should always be the case I think `Parameterized` should subclass `Serializable` to enforce it. Either that or fix it in a way that enables subclassing only `Parameterized`, but that seems more involved.

**Comment by dementrock** [comment]
Yes, Parameterized should extend Serializable. Would you be interested in submitting a pull request?

**Comment by sytham** [comment]
Yeah. Turns out there's another Parameterized in `sandbox.rocky.tf.core.parameterized`. What about that one?

**Comment by dementrock** [comment]
Yes, that one should also extend Serializable.
