### ISSUE TITLE
AttributeError: 'EnvSpec' object has no attribute 'action_space' when making custom environmnet

### ISSUE THREAD

**Issue by gasiort** [openai/rllab#125]
Environmnet get registered. Then command  `env = make(args.env)` is executed. After that env object has atrributes  'action_space' and 'observation_space'. But env.spec doesn't have them.

code:
```
env = make(args.env)
# print('observations space type = {}'.format(env.observation_space))
# print('actions space type = {}'.format(env.action_space))
# observations space type = Box(79,)
# actions space type = Box(9,)
policy = GaussianMLPPolicy(
    env_spec=env.spec,
)
```

> Traceback (most recent call last):
>   File "/home/usr/rllab/trpo_jaco.py", line 76, in <module>
>     env_spec=env.spec,
>   File "/home/user/rllab/rllab/policies/gaussian_mlp_policy.py", line 55, in __init__
>     assert isinstance(env_spec.action_space, Box)
> AttributeError: 'EnvSpec' object has no attribute 'action_space'

**Comment by dementrock** [comment]
The proper way is to use a GymEnv: https://github.com/openai/rllab/blob/master/examples/trpo_gym_cartpole.py
