### ISSUE TITLE
Why increase the recursion limit in rllab/misc/ext.py?

### ISSUE THREAD

**Issue by robertnishihara** [openai/rllab#127]
I'm curious about the line here https://github.com/openai/rllab/blob/872511883f1c415bb933e612a2a5b622c56be9b2/rllab/misc/ext.py#L11. What goes wrong if you omit that line?

This can turn some exceptions into segfaults.

For example,

```python
import cloudpickle
import rllab.misc.ext

class Foo(object):
  def __init__(self):
    super()

cloudpickle.dumps(Foo)  # This segfaults.
```

However, if you uncomment `import rllab.misc.ext` then it raises an exception

```
PicklingError: Could not pickle object as excessively deep recursion required.
```

I came across this in ray-project/ray#497.

**Comment by dementrock** [comment]
I vaguely recall that it was due to theano compiling computation graphs. However it should be totally fine to comment it out until things break because of recursion limit.

**Comment by robertnishihara** [comment]
I see, thanks!
