### ISSUE TITLE
the less frequently the gym make videos the longer it takes to record them

### ISSUE THREAD

**Issue by gasiort** [openai/rllab#137]
Hi, I am experiencing strange behaviour when setting video_schedule parameter in GymEnv. 
```
step = 20000
video_schedule = lambda episode_id: episode_id % step == 0
env = normalize(GymEnv(args.env, log_dir='/tmp/videos/trpo_rllab', video_schedule=video_schedule))
```
the bigger the step is the longer it takes to record video. Anyone had the same bug?

**Comment by dementrock** [comment]
What environment is this? If later episodes are longer then surely recording will take longer.

**Comment by gasiort** [comment]
It's custom, mujoco based, environment. Recording time is proportional to the `step` value. For instance, with `step=20000` it takes 45 minutes to record. 

I'm just wondering if someone encountered similar issue.
