### ISSUE TITLE
TF CategoricalGRUPolicy:  'GRUNetwork object has no attribute 'step_prev_hidden_layer''

### ISSUE THREAD

**Issue by boyentenbi** [openai/rllab#141]
I'm trying to instantiate a tensorflow CategoricalGRUPolicy object for the first time from `sandbox/rocky/tf/policies/categorical_gru_policy.py`. The console prints: `AttributeError: GRUNetwork object has no attribute 'step_prev_hidden_layer`. This seems like something that can't possibly be missed by anyone trying to use the class, so I may be doing something obviously wrong. 

However, from the code in `sandbox/rocky/tf/core/network` for GRUNetwork it looks like the reference in CategoricalGRUPolicy should be `prob_network.step_prev_state_layer` instead of `prob_network.step_prev_hidden_layer`. When I make this change locally the instantiation works, although I am having another issue with training which, if related, would mean that this hasn't actually fixed anything.

**Comment by dementrock** [comment]
Seems like this could be a bug introduced by the recent TF 1.0 update. You're right that it should be step_prev_state_layer. What other issue of training are you observing?

**Comment by boyentenbi** [comment]
No problem, here's the other issue I'm getting: 

```
/home/peter/anaconda2/envs/rllab3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in get_attr(self, name)
   1518       raise ValueError("No attr named '" + name + "' in " +
-> 1519                        str(self._node_def))
   1520     x = self._node_def.attr[name]

ValueError: No attr named '_XlaCompile' in name: "gradients_1/scan/while/MatMul/Enter_grad/b_acc_3"
op: "Exit"
input: "gradients_1/scan/while/MatMul/Enter_grad/Switch"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
```
Furthermore, another exception is thrown in the handling of this error: `TypeError: Second-order gradient for while loops not supported.`

This happens when rllab is trying to compute the descent direction. I'm using a LinearFeatureBaseline, a CategoricalGRUPolicy with the fix from above and TRPO. This also looks like it could also be a problem with the new version of TF. 

As a workaround I could try reverting to an older version, although I suspect it may be more useful for me to keep digging up bugs. What do you recommend?

**Comment by dementrock** [comment]
This is because TRPO uses second order information when computing hessian-vector products, and this is not supported in TF for control loop ops. To fix this you need to use finite difference to compute these hessian-vector products. Example: https://github.com/openai/rllab/blob/master/sandbox/rocky/tf/launchers/trpo_cartpole_recurrent.py#L32

**Comment by boyentenbi** [comment]
Got it working, cheers. 

In the appendix (C.1) of the TRPO paper, an algorithm for computing the hessian-vector products in the case of a KL constraint is given. My understanding was that it doesn't require second order derivatives with respect to the model parameters, but FiniteDifferenceHvp seems to be approximating these. 

Is FiniteDifferenceHvp implementing a different algorithm to the one I mentioned, or have I misunderstood something? (If they are different, I could try and write the one from the paper).

**Comment by dementrock** [comment]
There are multiple ways to do this, but as far as I know there's no way to do it exactly in TF for control-loop ops (for one thing, right multiplying by J is called "Rop," and is only implemented in Theano). However for a fixed horizon RNN it is possible. It might just be very slow since the unrolled graph is very large.

**Comment by boyentenbi** [comment]
Just found the issue you brought up on the tf repo, will stick with finite differences for now. Thanks for all the help.
