### ISSUE TITLE
Saving Trained Networks

### ISSUE THREAD

**Issue by cynthiatliu** [openai/rllab#35]
Hi,

How would one save a trained agent (say, ddpg)? Thank you,

**Comment by dementrock** [comment]
If you run under stub mode, for ddpg it will save per epoch a pkl file with the current policy and a bunch of other parameters (see https://github.com/rllab/rllab/blob/master/rllab/algos/ddpg.py#L455). Similar for other algorithms. You can find the saved file in the corresponding experiment folder.
