### ISSUE TITLE
Some numpy functions produce fatal error with rllab

### ISSUE THREAD

**Issue by aravindr93** [openai/rllab#37]
Hi, When using some functions from rllab, I'm unable to call a few numpy function. See below for an illustration.

```
from rllab.algos.trpo import TRPO
import numpy as np

Mu = np.array([0.0, 0.0])
Sigma = np.diag(np.array([1.0, 1.0]))
np.random.multivariate_normal(Mu, Sigma)
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.
```

Of course, the numpy functions work correctly if I am not importing rllab function. Any idea why this might be the case, and any hints on how to fix this. Unfortunately, what I'm doing requires me to both draw multivariate Gaussians and also use rllab functions at the same time. Thanks!

**Comment by dementrock** [comment]
@aravindr93 I've only had this error once and reinstalling Anaconda solved it for me. Could you try this and see if it works?

**Comment by Xingyu-Lin** [comment]
Same issue. Can be run locally but the docker mode or ec2 will run into the "Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so." error
