### ISSUE TITLE
How to render the environment?

### ISSUE THREAD

**Issue by lchenat** [openai/rllab#41]
Hi, can I render the box2D tasks during the training? I could not find relevant parameters in algo class.

**Comment by dementrock** [comment]
Does setting `plot=True` work?

https://github.com/rllab/rllab/blob/master/examples/trpo_cartpole_stub.py#L29

**Comment by lchenat** [comment]
I first got a None type object error. It worked after I added 'plotter.init_worker()' in start_worker() in batch_polopt.py . Thanks!

**Comment by dementrock** [comment]
Interesting. Did you uncomment both lines of plot=True?

**Comment by lchenat** [comment]
Oh, I did not uncomment the second line. It worked after both lines are uncommented. Thanks.

**Comment by lchenat** [comment]
In fact I did not use run_experiment_lite() in my program. If I only uncomment the first line and then call algo.train() I will get None type object error.
