### ISSUE TITLE
NameError: name 'instrument2' is not defined

### ISSUE THREAD

**Issue by vpong** [openai/rllab#44]
`rllab/misc/logger.py:256` has the following line:

        from rllab.misc import instrument2

I'm getting a NameError error at this statement. It looks like this was introduced in [this recent commit](https://github.com/openai/rllab/commit/872511883f1c415bb933e612a2a5b622c56be9b2). It doesn't look like any of the branches have a `rllab/misc/instrument2.py` module. Was this file left out of this commit, or am I missing something?

**Comment by dementrock** [comment]
Oops. I decided that `instrument2.py` was not useful to be released since it was slower than the default, but overlooked these references. Fixed in 9081c007b26b03ef9f8086be0a2eda6717f0c8b6.
