### ISSUE TITLE
Creating a setup.py so one can install rllab

### ISSUE THREAD

**Issue by paulhendricks** [openai/rllab#53]
Is there an initiative to create a `setup.py` file? I've drafted an example file here: https://gist.github.com/paulhendricks/f5da8cfdd91be93dbf4b03648d947ac3

This would be useful for running experiments and examples without needing all the rllab package files present. If this is useful, I can take a stab at implementing this and submit a pull request.

**Comment by dementrock** [comment]
That sounds very useful! Feel free to submit a pull request.

**Comment by weiliu620** [comment]
Would be great to have such feature. I guess I don't need to install conda in order to use rllab, if I have this ```setup.py```?

**Comment by paulhendricks** [comment]
Nope, just run:

```shell
python setup.py install
````

@dementrock: I've implemented a very basic one, no more than a couple lines. We can add more to it if need be.

**Comment by dementrock** [comment]
Saw the pull request. Thanks!
