### ISSUE TITLE
Can CategoricalGRUPolicy taking an initial hidden state

### ISSUE THREAD

**Issue by windweller** [openai/rllab#57]
Hi,

I'm working with the `sandbox/rocky/tf/policies/` directory

and the GRU Policies as I can recall, must have an initial hidden state (normally initialized randomly). However, is it possible for me to pass in the initial hidden state?

The algorithm I'm trying to run is VPG.

**Comment by dementrock** [comment]
You need to change the code slightly. Specifically after prob_network is constructed, and while running inside a tf.Session, you can set policy.prob_network.hid_init_param to some custom value.

**Comment by windweller** [comment]
I found "hid_init_param" in policy's reset() method, so now I'm thinking whenever reset() is called, instead of putting hid_init_param to 0, I just assign my own custom values to it.

The custom initialization of h0 depends on the data though. I'm keeping track of data in Env (with a list), and policy has access to Env. The only thing I worry is this kind of tracking is very sequential, and will result in dead-lock if any parallel processing is involved...is there a better way to handle this?

**Comment by dementrock** [comment]
I don't understand. Why would this result in dead-lock?

**Comment by windweller** [comment]
I thought VectorizedSampler is parallel, but I just checked the code again and it's not! I guess it should be fine! Thank you!
