### ISSUE TITLE
No Acrobot Env?

### ISSUE THREAD

**Issue by ir5** [openai/rllab#66]
I'm trying to run experiment on rllab environments, and I found that "Acrobot Swing Up" task is not defined in any files in `rllab/envs/box2d` directory. Did you intentionally exclude Acrobot environment for some reason? Or is this some mistake?

**Comment by dementrock** [comment]
It was named differently. It is the same as https://github.com/openai/rllab/blob/master/rllab/envs/mujoco/inverted_double_pendulum_env.py.

**Comment by ir5** [comment]
I see. Thank you for information.
