### ISSUE TITLE
EC2+GPU nvidia-docker not found

### ISSUE THREAD

**Issue by leduckhc** [openai/rllab#69]
Hi, I received error while running EC2 with GPU on `us-west-1 ami-7ea27a1e`
`/var/lib/cloud/instance/scripts/part-001: line 47: nvidia-docker: command not found`
 Running in the stubbed mode with
```
run_experiment_lite(
    algo.train(),
    exp_prefix="space-invaders",
    exp_name="dqn",
    # Number of parallel workers for sampling
    n_parallel=8,
    # Only keep the snapshot parameters for the last iteration
    snapshot_mode="all",
    mode="ec2",
    use_gpu=True,
    # Specifies the seed for the experiment. If this is not provided, a random seed
    # will be used
    seed=1,
    # plot=True,
    sync_s3_pkl=True,
    periodic_sync=True,
    periodic_sync_interval=120,
)
```

After checking AWS EC2 console (web) i find terminated instance. Thus I go to S3 container and open stdout.log and find these lines

```
sync initiated
log sync initiated
docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container did not start before the specified timeout".
upload: ../../../home/ubuntu/user_data.log to s3://rllab-rocky/experiments/first-exp/first_exp_2016_10_05_17_52_21_0001/stdout.log
{
    "return": "true"
}
{
    "return": "true"
}
start: Job is already running: docker
Using default tag: latest
latest: Pulling from dementrock/rllab3-shared
...
/var/lib/cloud/instance/scripts/part-001: line 47: nvidia-docker: command not found
```

**Comment by leduckhc** [comment]
Another issue is related to docker images `dementrock/rllab3-shared` and probably `dementrock/rllab3-shared-gpu` as well which don't have updated version of `gym`. Would you consider to upade the images?

**Comment by dementrock** [comment]
Yes, that AMI was supposed to work with CPU machines only. I will rollout a list of new AMIs / docker images soon.

**Comment by leduckhc** [comment]
Thank you in advance.

**Comment by dementrock** [comment]
I have updated all AMIs. Please find the new AMI ids here: https://github.com/openai/rllab/blob/master/scripts/setup_ec2_for_rllab.py#L50
