### ISSUE TITLE
Building docker file

### ISSUE THREAD

**Issue by dd210** [openai/rllab#75]
When trying to build image from docker/dockerfile, I get the error:

Input:

`docker build -t docker-rllab .`

Output:
```
Step 23/30 : ADD environment.yml /root/code/environment.yml
lstat environment.yml: no such file or directory
```
How it can be fixed?

**Comment by dd210** [comment]
Probably my error. Seemed it was enough to move dockerfile one level up. Closing the issue.

**Comment by mjm522** [comment]
I too got a similar issue. After searching a file this solved [this](https://github.com/docker/for-linux/issues/90) issue. 

docker build . -f  docker/gpu_tf_Dockerfile

The dot (.) is important.
