### ISSUE TITLE
How to get the params of l_log_std network used in GaussianMLPPolicy ?

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [openai/rllab#78]
I am trying to get the params of `l_log_std` network/layer given [here](https://github.com/openai/rllab/blob/master/rllab/policies/gaussian_mlp_policy.py#L88).

I am trying something like:
```python
std_param = L.get_all_params(self._l_log_std, trainable=True)
print std_param
w_std = std_param[0].get_value()
print type(w_std), w_std.shape
print w_std
```
The output is:
```
[output_log_std.param]
<type 'numpy.ndarray'> (3,)
[-0.87651855 -0.65048313 -0.84686345]
```
But I am expecting a matrix **num_inputs x num_units**. I am running hopper-v1 of openai gym,
where **num_inputs = 11** and **num_units = 3**.

Could someone please tell me how to get the weights of this network/layer ?

**Comment by dementrock** [comment]
Hi @sarvjeetsinghghotra, by default the standard deviation is constant across different inputs, and there is no network for it. There's exactly one entry per action dimension.
