### ISSUE TITLE
Parameter meanings in algorithms

### ISSUE THREAD

**Issue by dqii** [openai/rllab#94]
algo = DDPG(
        env=env,
        policy=policy,
        es=es,
        qf=qf,
        batch_size=32,
        max_path_length=100,
        epoch_length=1000,
        min_pool_size=10000,
        n_epochs=1000,
        discount=0.99,
        scale_reward=0.01,
        qf_learning_rate=1e-3,
        policy_learning_rate=1e-4,
        # Uncomment both lines (this and the plot parameter below) to enable plotting
        # plot=True,
    )

Could someone explain what max_path_length, epoch_length, and n_epochs mean? Sorry I am confused. :(

**Comment by dementrock** [comment]
max_path_length: maximum length of each rollout
epoch_length: number of updates per epoch (basically, how often to print logs)
n_epochs: number of epochs
