### ISSUE TITLE
Implementation of GRUNetwork

### ISSUE THREAD

**Issue by lchenat** [openai/rllab#99]
In GRUNetwork, it has separate output DenseLayer (l_output_flat and l_step_output). In gaussian_gru_policy, it uses l_output (l_output_flat) in dist_info_sym. It seems that the parameters of l_step_output layer will not get updated. Wouldn't that be a problem?

**Comment by dementrock** [comment]
l_step_output and l_output_flat shares parameters. Assuming you are talking about the theano version: https://github.com/openai/rllab/blob/master/rllab/core/network.py#L227

**Comment by lchenat** [comment]
Oh, I see! Thanks.
